/**
 * @file opcode.h
 *
 * @brief Defines JIT IR opcodes and their metadata.
 *
 * The actual definitions of opcodes and their metadata are generated
 * by including "opcode.inc", which is processed using X-macros.
 */

#ifndef POUMD_JIT_IR_OPCODE_H
#define POUMD_JIT_IR_OPCODE_H
#include "type.h"

// The maximum number of argument types an IR opcode can have.
#define OPCODE_ARGS_TYPES_SIZE 4

/*!
 * @brief Enumeration of all microinstructions (opcodes) in the JIT IR.
 *
 * Each enum value corresponds to a specific operation that can be
 * performed by the JIT, such as arithmetic operations, memory accesses,
 * or system register manipulations.
 *
 * The enum values are generated by including "opcode.inc" and using
 * the OPCODE and A32OPC macros. A64OPC is currently disabled.
 */
typedef enum
{
#define OPCODE(name, type, ...) OPCODE_##name,
#define A32OPC(name, type, ...) OPCODE_A32##name,
// #define A64OPC(name, type, ...) OPCODE_A64##name,
#include "./opcode.inc"
#undef OPCODE
#undef A32OPC
#undef A64OPC
    NUM_OPCODE
} pvm_jit_ir_opcode_t;

/*!
 * @brief Structure holding static metadata for an IR opcode.
 */
typedef struct
{
    const char       *name;
    pvm_jit_ir_type_t type;
    pvm_jit_ir_type_t arg_types[OPCODE_ARGS_TYPES_SIZE];
} pvm_jit_ir_decoded_opcode_t;

/*!
 * @brief Global array of `pvm_jit_ir_decoded_opcode_t` structures for all
 * opcodes.
 *
 * This array is indexed by the `pvm_jit_ir_opcode_t` enum values, providing a
 * direct lookup for opcode metadata. For example,
 * `g_pvm_jit_ir_opcodes[OPCODE_Add32].name` would yield "Add32".
 */
extern pvm_jit_ir_decoded_opcode_t g_pvm_jit_ir_opcodes[NUM_OPCODE];
#endif // POUMD_JIT_IR_OPCODE_H
